### PR TITLE
Resolves #3 and #5

### LINKED ISSUE #3: click dependency not bounded
OS: Windows 10 21H2
Python: Python 3.10.4

Steps:
   - pip install "click<7"
   - pip install pyquotes

example.py
```python
print("Hello, World!")
```

pyquotes --check example.py
pyquotes -D --check example.py

Both fail with the error
```
  File "C:\Python310\lib\site-packages\pyquotes\settings.py", line 96, in __init__
    super().__init__(**settings, project_root=project_root)
TypeError: _Config.__init__() got an unexpected keyword argument 'check'
```

This is resolved when using ``click>=8``.

Thank you for your time, this library has saved my many hours.

### PR DESCRIPTION
**Pull request by ghost**
- #3 Added a minimum version of click
- #5 Force UTF-8 encoding on reading/writing

I have not bumped version, and will leave that to you pending acceptance of these changes.

Thank you.

### CODE REVIEW

**Comment by ghost** [comment]
I don't seem to be able to run the workflow, after the weekend hopefully you can give it a nudge, thank you!

**Comment by ghost** [comment]
Thanks for triggering the tests, I'm not sure why they're failing, it's an area of the code base I haven't touched. Any ideas?

**Comment by ThiefMaster** [comment]
they seem to be unrelated to your changes. i'll have a look later

**Comment by ghost** [comment]
> they seem to be unrelated to your changes. i'll have a look later

Is there anything I need to do?

**Comment by ThiefMaster** [comment]
sorry, didn't have time yet

**Comment by ghost** [comment]
> sorry, didn't have time yet

No worries! Just checking I wasn't holding it up :)

**Pull request closed without merging**
